image: jitpack/android

before_install:
  - echo "Starting JitCI Build for HarmonicMapper"

  install:
    - ./gradlew dependencies

    build:
      script:
          - chmod +x ./gradlew
              - ./gradlew assembleDebug

              artifacts:
                paths:
                    - app/build/outputs/apk/debug/app-debug.apk